### ISSUE TITLE
LoggingInterceptor crashes due missing `request.customer_id` for `get_campaign_budget`

### ISSUE THREAD

**Issue by jbodah** [googleads/google-ads-ruby#35] opened 2019-02-08 15:11 UTC
With `google-gax` v1.5.0

This code is crashing for us:

https://github.com/googleads/google-ads-ruby/blob/b925f8a1dadfe871a43b2f476e4f6496a617b853/lib/google/ads/google_ads/logging_interceptor.rb#L31-L37

When we call `service.get_campaign_budget("customers/#{id1}/campaignBudgets/#{id2}")`:

https://github.com/googleads/google-ads-ruby/blob/b925f8a1dadfe871a43b2f476e4f6496a617b853/lib/google/ads/google_ads/v0/services/campaign_budget_service_client.rb#L211-L220

Because `Google::Gax::to_proto` is not returning an object that responds to `customer_id`:

```
[7] pry(#<#<Class:0x00000000068d0300>>)> Google::Gax::to_proto({resource_name: resource_name}, Google::Ads::GoogleAds::V0::Services::GetCampaignBudgetRequest)
=> <Google::Ads::GoogleAds::V0::Services::GetCampaignBudgetRequest: resource_name: "customers/REMOVED_ID1/campaignBudgets/REMOVED_ID2">
```

**Comment by mcloonan** [comment] 2019-02-08 15:22
duplicate of #26

**Closed by mcloonan** 2019-02-08 15:22 UTC
