### ISSUE TITLE
Infinite loop when using invalid refresh_token

### ISSUE THREAD

**Issue by evgeniy-b** [googleads/google-ads-ruby#99] opened 2019-04-29 15:36 UTC
When the refresh token is invalid, client goes into an infinite loop instead of raising exceptions:

```
[3] pry(main)> client.service(:Customer).list_accessible_customers

W, [2019-04-29T15:28:27.286127 #41]  WARN -- : CID: N/A, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v1.services.CustomerService/ListAccessibleCustomers, IsFault: yes
I, [2019-04-29T15:28:27.286886 #41]  INFO -- : Outgoing request: Headers: {"x-goog-api-client":"gl-ruby/2.6.3 gapic/1.1.1 gax/1.5.0 grpc/1.20.0","developer-token":"hidden"} Payload: {}
I, [2019-04-29T15:28:27.287015 #41]  INFO -- : Incoming response (errors):
Could not parse error details due to a malformed server response trailer.
W, [2019-04-29T15:28:27.488532 #41]  WARN -- : CID: N/A, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v1.services.CustomerService/ListAccessibleCustomers, IsFault: yes
I, [2019-04-29T15:28:27.488826 #41]  INFO -- : Outgoing request: Headers: {"x-goog-api-client":"gl-ruby/2.6.3 gapic/1.1.1 gax/1.5.0 grpc/1.20.0","developer-token":"hidden"} Payload: {}
I, [2019-04-29T15:28:27.489125 #41]  INFO -- : Incoming response (errors):
Could not parse error details due to a malformed server response trailer.
W, [2019-04-29T15:28:27.625463 #41]  WARN -- : CID: N/A, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v1.services.CustomerService/ListAccessibleCustomers, IsFault: yes
I, [2019-04-29T15:28:27.625792 #41]  INFO -- : Outgoing request: Headers: {"x-goog-api-client":"gl-ruby/2.6.3 gapic/1.1.1 gax/1.5.0 grpc/1.20.0","developer-token":"hidden"} Payload: {}
I, [2019-04-29T15:28:27.626775 #41]  INFO -- : Incoming response (errors):
Could not parse error details due to a malformed server response trailer.
```

**Comment by mcloonan** [comment] 2019-04-29 15:59
I'm also able to reproduce. I think this is an issue with the underlying gax library, since we just pass the refresh token along there. I'll check with that team to see what we can do.

**Comment by evgeniy-b** [comment] 2019-04-29 16:12
Thanks!
Also would be great to be able to have more authentication options than only refresh_token (without monkey-patching). For example, using simply access token.

**Comment by mcloonan** [comment] 2019-04-29 16:14
What is the use case where you'd want to provide your own access token? Access tokens are only good for an hour, and require a refresh token to generate, so it seems like the convenience of letting the library handle it for you would be pretty appealing.

**Comment by evgeniy-b** [comment] 2019-04-30 08:48
In our case we have one service responsible for storing/refreshing tokens and many other services using access tokens. So each service doesn't have to store all the secrets, handle errors and also access tokens are requested just once per hour.
It would be great not to limit the [authorization options](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/services/account_budget_service_client.rb#L78) solely to refresh token since they are already there.

**Comment by mcloonan** [comment] 2019-04-30 11:53
That sounds reasonable. I think we can expose an interface to allow you to define your own credentials to be passed to the service. I'll open a new issue for that feature request, and we can leave this one for the infinite loop.

**Comment by qnm** [comment] 2020-11-02 02:19
Any updates on this? Any workarounds? I experienced it recently. 

My intention is to use this in a worker queue, and if it loops infinitely I will be unable to to resolve it without intervention.

**Comment by mcloonan** [comment] 2021-03-22 16:37
Going to close this as a duplicate of issue #246 since that one has more specific information.

**Closed by mcloonan** 2021-03-22 16:37 UTC
